# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-13 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Learned_Present',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=255, unique=True, verbose_name='Present')),
                ('category', models.CharField(default='Regular', max_length=255, verbose_name='Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
        ),
        migrations.CreateModel(
            name='LearnedWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, max_length=255, null=True, verbose_name='Palabra aprendida')),
            ],
        ),
        migrations.CreateModel(
            name='Past',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=255, unique=True, verbose_name='Past')),
            ],
        ),
        migrations.CreateModel(
            name='PastParticiple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=255, unique=True, verbose_name='Past participle')),
            ],
        ),
        migrations.CreateModel(
            name='Present',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=255, unique=True, verbose_name='Present')),
                ('category', models.CharField(default='Regular', max_length=255, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la rutina')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('VERBS', 'VERBS'), ('--------------------', '--------------------')], default='--------------------', max_length=512, unique=True, verbose_name='Tema')),
                ('repetitions', models.IntegerField(default=5, verbose_name='Repeticiones')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practise.Routine', verbose_name='Rutina')),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, verbose_name='Palabra')),
                ('learned', models.BooleanField(default=False, verbose_name='¿Aprendido?')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practise.Topic', verbose_name='Tema')),
            ],
        ),
        migrations.AddField(
            model_name='pastparticiple',
            name='present',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practise.Present', verbose_name='Present'),
        ),
        migrations.AddField(
            model_name='past',
            name='present',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practise.Present', verbose_name='Present'),
        ),
        migrations.AddField(
            model_name='learnedword',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practise.Topic', verbose_name='Tema'),
        ),
    ]
