# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-02 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtherTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=255, verbose_name='Present')),
                ('time', models.CharField(choices=[(b'Irregular', b'Irregular'), (b'Regular', b'Regular'), (b'Phrasal Verb', b'Phrasal Verb')], default=b'Regular', max_length=255, verbose_name='Time')),
            ],
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.CharField(max_length=255, verbose_name='Present')),
                ('category', models.CharField(choices=[(b'Irregular', b'Irregular'), (b'Regular', b'Regular'), (b'Phrasal Verb', b'Phrasal Verb')], default=b'Regular', max_length=255, verbose_name='Type')),
            ],
        ),
        migrations.AddField(
            model_name='othertime',
            name='present',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practise.Verb', verbose_name='Present'),
        ),
    ]
