# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-14 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentencePresent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(unique=True, verbose_name='Sentence')),
                ('secondary_id', models.CharField(max_length=50, verbose_name='Secondary Id')),
                ('auxiliary', models.CharField(max_length=50, verbose_name='Auxiliary')),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practise.Present', verbose_name='Present')),
            ],
        ),
        migrations.RenameModel(
            old_name='Learned_Present',
            new_name='LearnedPresent',
        ),
    ]
