# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othertime',
            name='time',
            field=models.CharField(choices=[(b'Past', b'Past'), (b'Past Participle', b'Past Participle')], default=b'Past', max_length=255, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='present',
            field=models.CharField(max_length=255, unique=True, verbose_name='Present'),
        ),
    ]
