# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0002_auto_20180209_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Past',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=255, unique=True, verbose_name='past')),
            ],
        ),
        migrations.CreateModel(
            name='PastParticiple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=255, unique=True, verbose_name='past_participle')),
            ],
        ),
        migrations.CreateModel(
            name='Present',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=255, unique=True, verbose_name='Present')),
                ('category', models.CharField(default=b'Regular', max_length=255, verbose_name='Type')),
            ],
        ),
        migrations.AlterField(
            model_name='othertime',
            name='present',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practise.Present', verbose_name='Present'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='category',
            field=models.CharField(choices=[(b'Irregular', b'Irregular'), (b'Regular', b'Regular')], default=b'Regular', max_length=255, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='pastparticiple',
            name='present',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practise.Present', verbose_name='Present'),
        ),
        migrations.AddField(
            model_name='past',
            name='present',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practise.Present', verbose_name='Present'),
        ),
    ]
