# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0003_auto_20180209_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othertime',
            name='present',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practise.Verb', verbose_name='Present'),
        ),
    ]
