# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0004_auto_20180209_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othertime',
            name='present',
        ),
        migrations.DeleteModel(
            name='OtherTime',
        ),
        migrations.DeleteModel(
            name='Verb',
        ),
    ]
