# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-01 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0004_delete_presente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=255, unique=True, verbose_name='Past')),
                ('present', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practise.Present', verbose_name='Present')),
            ],
        ),
    ]
