# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0005_auto_20180209_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la rutina')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'VERBS', b'VERBS')], default=b'--------------------', max_length=512, unique=True, verbose_name='Tema')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practise.Routine', verbose_name='Rutina')),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, verbose_name='Palabra')),
                ('learned', models.BooleanField(default=False, verbose_name='\xbfAprendido?')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practise.Topic', verbose_name='Tema')),
            ],
        ),
        migrations.AlterField(
            model_name='past',
            name='verb',
            field=models.CharField(max_length=255, unique=True, verbose_name='Past'),
        ),
        migrations.AlterField(
            model_name='pastparticiple',
            name='verb',
            field=models.CharField(max_length=255, unique=True, verbose_name='Past participle'),
        ),
    ]
