# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-12 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0008_auto_20180210_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='present',
            name='category',
            field=models.CharField(default='Regular', max_length=255, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(choices=[('VERBS', 'VERBS'), ('--------------------', '--------------------')], default='--------------------', max_length=512, unique=True, verbose_name='Tema'),
        ),
    ]
