# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-01 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0008_auto_20180701_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhrasalVerb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrasal_verb', models.CharField(max_length=255, unique=True, verbose_name='Phrasal Verb')),
                ('category', models.CharField(default='Phrasal_verb', max_length=255, verbose_name='Type')),
            ],
        ),
    ]
