# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-13 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practise', '0009_auto_20180612_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='learned_Present',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=255, unique=True, verbose_name='Present')),
                ('category', models.CharField(default='Regular', max_length=255, verbose_name='Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
        ),
    ]
