# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-09 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0010_routine_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='learned_word',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Palabra aprendida'),
        ),
    ]
