# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-01 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0011_presente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Presente',
        ),
    ]
