# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-10 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0011_topic_learned_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnedWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, max_length=255, null=True, verbose_name='Palabra aprendida')),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='learned_word',
        ),
        migrations.AddField(
            model_name='learnedword',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practise.Topic', verbose_name='Tema'),
        ),
    ]
