# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-10 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0012_auto_20180510_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnedword',
            old_name='routine',
            new_name='topic',
        ),
    ]
