# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-01 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0013_presente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrasalverb',
            name='category',
        ),
    ]
