# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-10 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0014_routine_repetitions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='repetitions',
        ),
        migrations.AddField(
            model_name='topic',
            name='repetitions',
            field=models.IntegerField(default=5, verbose_name='Repeticiones'),
        ),
    ]
