# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-01 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0015_auto_20180701_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='present',
            name='verb',
            field=models.CharField(max_length=255, unique=True, verbose_name='Present'),
        ),
    ]
