# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-01 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0016_auto_20180701_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='present',
            name='category2',
            field=models.CharField(default='Regular', max_length=255, verbose_name='Type'),
        ),
    ]
