# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-01 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0017_present_category2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='present',
            name='category2',
        ),
    ]
