# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-01 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0018_remove_present_category2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='past',
            name='verb',
            field=models.CharField(max_length=255, unique=True, verbose_name='Pasta'),
        ),
    ]
