# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-05 23:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practise', '0020_auto_20180701_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnedPhrasal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrasal', models.CharField(max_length=255, unique=True, verbose_name='phrasal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
        ),
    ]
